
services:
  - type: web
    name: bgs-ai-bot
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: RNN_PATH
        value: "models/rnn_model.h5"
      - key: XGB_PATH
        value: "models/xgb_model.pkl"
      - key: LGBM_PATH
        value: "models/lgbm_model.pkl"
      - key: RNN_MIN_SEQ
        value: "10"
      - key: XGB_MIN_SEQ
        value: "6"
      - key: LGBM_MIN_SEQ
        value: "6"
      - key: RULE_W
        value: "0.5"
      - key: RNN_W
        value: "0.3"
      - key: XGB_W
        value: "0.15"
      - key: LGBM_W
        value: "0.05"
      - key: FEAT_WIN
        value: "20"
      - key: CLASS_ORDER
        value: "B,P,T"
    healthCheckPath: /health
