services:
  - type: web
    name: bgs-outcome-only
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers=1 --threads=8 --timeout=120 --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TZ
        value: Asia/Taipei
      - key: WEB_CONCURRENCY
        value: "1"
      # 試用與運營
      - key: TRIAL_MINUTES
        value: "30"
      - key: ADMIN_CONTACT
        value: "@admin"
      - key: ADMIN_ACTIVATION_SECRET
        sync: false
      # OutcomePF 參數
      - key: DECKS
        value: "8"
      - key: PF_N
        value: "200"
      - key: PF_BACKEND
        value: "exact"    # exact 或 mc
      - key: PF_RESAMPLE
        value: "0.5"
      - key: PF_DIR_EPS
        value: "0.002"
      # 決策/資金
      - key: EDGE_ENTER
        value: "0.03"
      - key: USE_KELLY
        value: "1"
      - key: KELLY_FACTOR
        value: "0.25"
      - key: MAX_BET_PCT
        value: "0.015"
      # LINE（可選）
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
