services:
  # 主 Flask API + LINE Bot（整合於 app.py）
  - type: web
    name: baccarat-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
      # 建議直接在 Render Dashboard 加入下列環境變數
      # - key: LINE_CHANNEL_ACCESS_TOKEN
      #   sync: false
      # - key: LINE_CHANNEL_SECRET
      #   sync: false
      # - key: BACKEND_URL
      #   value: https://baccarat-ai-backend.onrender.com

  # Worker：負責執行 monitor.py，持續爬取前端頁面並推送路子
  - type: worker
    name: baccarat-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      # Worker 也需要知道 API 的位置
      - key: BACKEND_URL
        value: https://baccarat-ai-backend.onrender.com
