services:
  - type: web
    name: bgs-ai-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: DEBUG_VISION
        value: "0"
      # 颜色检测参数 - 红色1
      - key: HSV_RED1_H_LOW
        value: "0"
      - key: HSV_RED1_S_LOW
        value: "100"
      - key: HSV_RED1_V_LOW
        value: "50"
      - key: HSV_RED1_H_HIGH
        value: "10"
      - key: HSV_RED1_S_HIGH
        value: "255"
      - key: HSV_RED1_V_HIGH
        value: "255"
      # 颜色检测参数 - 红色2
      - key: HSV_RED2_H_LOW
        value: "170"
      - key: HSV_RED2_S_LOW
        value: "100"
      - key: HSV_RED2_V_LOW
        value: "50"
      - key: HSV_RED2_H_HIGH
        value: "180"
      - key: HSV_RED2_S_HIGH
        value: "255"
      - key: HSV_RED2_V_HIGH
        value: "255"
      # 颜色检测参数 - 蓝色
      - key: HSV_BLUE_H_LOW
        value: "100"
      - key: HSV_BLUE_S_LOW
        value: "100"
      - key: HSV_BLUE_V_LOW
        value: "50"
      - key: HSV_BLUE_H_HIGH
        value: "140"
      - key: HSV_BLUE_S_HIGH
        value: "255"
      - key: HSV_BLUE_V_HIGH
        value: "255"
      # 颜色检测参数 - 绿色
      - key: HSV_GREEN_H_LOW
        value: "60"
      - key: HSV_GREEN_S_LOW
        value: "50"
      - key: HSV_GREEN_V_LOW
        value: "50"
      - key: HSV_GREEN_H_HIGH
        value: "90"
      - key: HSV_GREEN_S_HIGH
        value: "255"
      - key: HSV_GREEN_V_HIGH
        value: "200"
      # ROI设置
      - key: FOCUS_ROI
        value: "0.2,0.3,0.6,0.5"
      # 大路区域比例
      - key: BIGROAD_FRAC
        value: "0.70"
    healthCheckPath: /health
