# render.yaml
services:
  - type: web
    name: bgs-ai-bot
    env: python
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr tesseract-ocr-chi-sim tesseract-ocr-chi-tra
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: DEBUG_VISION
        value: "1"  # 啟用調試模式以獲取更多日誌
    healthCheckPath: /health
